### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by muesli**
Simple, nit-picky typo fixes.

### CODE REVIEW

**Comment by BurntSushi** [comment]
@muesli I appreciate that you're trying to improve things, but the PRs you've sent (to this project and others) are trivial fixes and this project is effectively in maintenance mode. While I don't disagree with these changes, I'd appreciate it if you didn't fill up my mailbox with a PR for every single little thing.

Please consider collecting all of your changes, broken down by commit, and submit _one_ PR once you're done.

**Comment by muesli** [comment]
@BurntSushi You're absolutely right, those are trivial fixes and it's a lot of boring grunt work. I'm sorry to have bothered you with these changes, but I'm intentionally keeping pull requests as granular as possible, because it makes it a lot easier to review, argue about, accept & reject them individually. I think that's commonly accepted as good practice. For what it's worth, I'm done posting PRs for your repositories, so your INBOX is all yours again :smile:

**Comment by BurntSushi** [comment]
I'd prefer them all in one PR. If I don't agree with a change, then you can just drop that commit from the PR.

**Comment by muesli** [comment]
But surely you understand that most other maintainers would disagree with that kind of pull request, no matter how small the individual commits inside it. It's also a whole lot easier for you to just click "Merge" or "Close" on individual pull requests than having to go back and forth with me multiple times on one big diff. That's just more error-prone, requires me to rewrite the commit history and force-push, and you to review the entire change-set again - after every single review iteration.

Feel free to ignore these changes should you consider them not important enough, but at this point it's still less work for you to click "Merge" or "Close" fives times, than me cherry-picking or rebasing from five branches and creating a new pull request (you'd still have to click "Close" on the old ones then).

Again, sorry for the noise, I honestly didn't mean to bother anyone.

**Comment by BurntSushi** [comment]
I'm not interested in having a debate about PR workflow. But no, I surely wouldn't agree with you.

I'm just going to close out the PRs. If you want to re-submit as fewer PRs, then that's fine.

**Pull request closed without merging**
